### ISSUE TITLE
Installation error: Property 'prompts' is used before its initialization.

### ISSUE THREAD

**Issue by flaaaps** [cmorten/opine-cli#1]
# Issue

Setup:

- Deno Version: 1.9.2
- v8 Version: 9.1.269.5
- Typescript Version: 4.2.2
- Opine CLI Version: N/A

## Details

> When i'm trying to install the CLI using `deno install -f -q --allow-read --allow-write --allow-net --unstable https://deno.land/x/opinecli@1.1.0/opine-cli.ts`, i'm getting the following TypeScript error: 

```bash
error: TS2729 [ERROR]: Property 'prompts' is used before its initialization.
  private names: string[] = this.prompts.map((prompt) => prompt.name);
                                 ~~~~~~~
    at https://deno.land/x/cliffy@v0.16.0/prompt/prompt.ts:2010:34

    'prompts' is declared here.
        private prompts: PromptOptions<string, any, any>[],
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/cliffy@v0.16.0/prompt/prompt.ts:2018:5
```

> Thanks in advance.

**Comment by cmorten** [comment]
Hi @flaaaps :wave:

Thanks for raising - Deno `^1.9.0` ( https://github.com/denoland/deno/releases/tag/v1.9.0 ) brought in some new changes which broke the `cliffy` package that this module uses. Should be resolved by https://github.com/cmorten/opine-cli/pull/2.

**Comment by cmorten** [comment]
Please re-open if still face issues with version `1.2.0`. If you're seeing similar dependency issues, try adding a `--reload` flag just in case something has gone amiss with your deno cache, e.g.

```console
deno install -f -q --allow-read --allow-write --allow-net --reload --unstable https://deno.land/x/opinecli@1.2.0/opine-cli.ts
```
