### ISSUE TITLE
Why is version 1.2 specified?  opinecli@1.3.0 

### ISSUE THREAD

**Issue by abedarev** [cmorten/opine-cli#3]
PS C:\deno2>  deno install -f -q --allow-read --allow-write --allow-net --unstable https://deno.land/x/opinecli@1.3.0/opine-cli.ts
✅ Successfully installed opine-cli
C:\Users\be-aa\.deno\bin\opine-cli.cmd
C:\Users\be-aa\.deno\bin\opine-cli (shell)
PS C:\deno2> opine-cli --version
1.2.0                                    Why is version 1.2 specified?  opinecli@1.3.0 

PS C:\deno2> deno --version
deno 1.16.3 (release, x86_64-pc-windows-msvc)
v8 9.7.106.5
typescript 4.4.2
PS C:\deno2> opine-cli --view=ejs hello-deno

   create : hello-deno\
   create : hello-deno\public\
   create : hello-deno\public\js\
   create : hello-deno\public\images\
   create : hello-deno\public\css\
   create : hello-deno\routes\
   create : hello-deno\views\
   create : hello-deno\routes\users.ts
   create : hello-deno\routes\index.ts
   create : hello-deno\public\css\style.css
   create : hello-deno\mod.ts
   create : hello-deno\app.ts
   create : hello-deno\views\error.ejs
   create : hello-deno\views\index.ejs
   create : hello-deno\deps.ts

   change directory:
     > cd hello-deno

   run the app:
     > deno run --allow-net --allow-read --allow-env mod.ts

PS C:\deno2> cd hello-deno
PS C:\deno2\hello-deno> deno run --allow-net --allow-read --allow-env mod.ts
Check file:///C:/deno2/hello-deno/mod.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.69.0/async/pool.ts:45:23
PS C:\deno2\hello-deno>

**Comment by cmorten** [comment]
Hey @abedarev 👋 

Sorry for the slow reply - I've just released https://deno.land/x/opinecli@2.0.0 which should now generated a starter application using the latest versions of dependencies including opine.
